Repository software-students-fall2021/rokietnica-logistical-app, pull requests merged in 2021-11, with the labels that each got.

#19 Add files via upload
  front-end/nycroute-app/src/Homepage.js
Labels: task

#22 Prelim work on list of stations view
  front-end/nycroute-app/package-lock.json
  front-end/nycroute-app/package.json
  front-end/nycroute-app/src/App.js
  front-end/nycroute-app/src/SubwayLineInfoItem.js
  front-end/nycroute-app/src/SubwayLinesInfo.css
  front-end/nycroute-app/src/SubwayLinesInfo.js
  front-end/nycroute-app/src/SubwayStationInfo.js
  front-end/nycroute-app/src/SubwayStationInfoItem.js
  front-end/nycroute-app/src/SubwayStations.css
  front-end/nycroute-app/src/SubwayStations.js
  front-end/nycroute-app/src/Test1.js
  front-end/nycroute-app/src/Test2.js
  front-end/nycroute-app/src/stationData.js
Labels: task

#23 Prelim work on station view
  front-end/nycroute-app/src/App.js
  front-end/nycroute-app/src/SubwayStation.css
  front-end/nycroute-app/src/SubwayStation.js
Labels: task

#25 Soojin c/backend setup
  back-end/app.js
  back-end/package-lock.json
  back-end/package.json
  back-end/server.js
Labels: spike

#20 Zhangj
  front-end/nycroute-app/src/Subwaylines.css
  front-end/nycroute-app/src/Subwaylines.js
Labels: task

#36 Link station items to respective station page
  front-end/nycroute-app/src/Homepage.js
  front-end/nycroute-app/src/SubwayStation.css
  front-end/nycroute-app/src/SubwayStation.js
  front-end/nycroute-app/src/SubwayStations.css
  front-end/nycroute-app/src/SubwayStations.js
  front-end/nycroute-app/src/stationData.js
Labels: user story, task

#37 Subway Station Page Frontend
  front-end/nycroute-app/src/LineCard.css
  front-end/nycroute-app/src/LineCard.js
  front-end/nycroute-app/src/SubwayStation.css
  front-end/nycroute-app/src/SubwayStation.js
  front-end/nycroute-app/src/line_icons/1.svg
  front-end/nycroute-app/src/line_icons/2.svg
  front-end/nycroute-app/src/line_icons/3.svg
  front-end/nycroute-app/src/line_icons/4.svg
  front-end/nycroute-app/src/line_icons/5.svg
  front-end/nycroute-app/src/line_icons/6.svg
  front-end/nycroute-app/src/line_icons/6d.svg
  front-end/nycroute-app/src/line_icons/7.svg
  front-end/nycroute-app/src/line_icons/7d.svg
  front-end/nycroute-app/src/line_icons/a.svg
  front-end/nycroute-app/src/line_icons/b.svg
  front-end/nycroute-app/src/line_icons/c.svg
  front-end/nycroute-app/src/line_icons/d.svg
  front-end/nycroute-app/src/line_icons/e.svg
  front-end/nycroute-app/src/line_icons/f.svg
  front-end/nycroute-app/src/line_icons/g.svg
  front-end/nycroute-app/src/line_icons/h.svg
  front-end/nycroute-app/src/line_icons/j.svg
  front-end/nycroute-app/src/line_icons/l.svg
  front-end/nycroute-app/src/line_icons/m.svg
  front-end/nycroute-app/src/line_icons/n.svg
  front-end/nycroute-app/src/line_icons/q.svg
  front-end/nycroute-app/src/line_icons/r.svg
  front-end/nycroute-app/src/line_icons/s.svg
  front-end/nycroute-app/src/line_icons/sf.svg
  front-end/nycroute-app/src/line_icons/sir.svg
  front-end/nycroute-app/src/line_icons/sr.svg
  front-end/nycroute-app/src/line_icons/t.svg
  front-end/nycroute-app/src/line_icons/w.svg
  front-end/nycroute-app/src/line_icons/z.svg
Labels: task

#39 Add Travis CI files and badge to README
  .travis.yml
  README.md
  front-end/nycroute-app/package-lock.json
  front-end/nycroute-app/package.json
  front-end/nycroute-app/src/App.test.js
Labels: spike
