Repository software-students-fall2021/rokietnica-logistical-app, pull requests merged in 2021-12, with the labels that each got.

#49 Add MTAPI Server
  .gitignore
  MTAPI-master/.gitignore
  MTAPI-master/README.md
  MTAPI-master/app.py
  MTAPI-master/conftest.py
  MTAPI-master/data/stations.csv
  MTAPI-master/data/stations.json
  MTAPI-master/docs/endpoints.md
  MTAPI-master/mtapi/__init__.py
  MTAPI-master/mtapi/_mtapithreader.py
  MTAPI-master/mtapi/mtapi.py
  MTAPI-master/mtaproto/__init__.py
  MTAPI-master/mtaproto/feedresponse.py
  MTAPI-master/mtaproto/gtfs-realtime.proto
  MTAPI-master/mtaproto/gtfs_realtime_pb2.py
  MTAPI-master/mtaproto/nyct-subway.proto
  MTAPI-master/mtaproto/nyct_subway_pb2.py
  MTAPI-master/requirements.txt
  MTAPI-master/scripts/make_stations_csv.py
  MTAPI-master/scripts/make_stations_json.py
  MTAPI-master/settings.cfg.sample
  MTAPI-master/tests/test_mtapi.py
  back-end/package-lock.json
  back-end/package.json
Labels: spike

#54 Realtime Station Data
  MTAPI-master/.gitignore
  MTAPI-master/settings.cfg
  back-end/app.js
  front-end/src/LineCard.css
  front-end/src/LineCard.js
  front-end/src/SubwayStation.css
  front-end/src/SubwayStation.js
  front-end/src/SubwayStationItem.css
  front-end/src/SubwayStationItem.js
  front-end/src/SubwayStations.css
  front-end/src/SubwayStations.js
  front-end/src/line_icons/5x.png
  front-end/src/line_icons/fx.png
Labels: user story, task, spike

#58 Update README.md
  README.md
Labels: task, spike

#55 Soojin c/db user data
  back-end/app.js
  back-end/jwt-config.js
  back-end/models/favLineModel.js
  back-end/models/favStationModel.js
  back-end/models/userModel.js
  back-end/package-lock.json
  back-end/package.json
  back-end/server.js
  back-end/test/App.test.js
  back-end/test/login.test.js
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/Homepage.css
  front-end/src/Homepage.js
  front-end/src/Login.js
  front-end/src/Logout.js
  front-end/src/NavBar.js
  front-end/src/Signup.js
  front-end/src/SubwayIcon.js
  front-end/src/SubwayLinesInfo.js
  front-end/src/SubwayLinesInfoItem.js
  front-end/src/SubwayStation.js
  front-end/src/SubwayStations.js
  front-end/src/Subwaylines.js
  front-end/src/TestBootStrap.js
Labels: user story, task, spike
